okhv = "OKH-LOSHv1.0"

name = "Smart Energy Monitor"
function = "A smart energy monitor to measure the power consumption"

version = "0.1"
repo = "https://code.curious.bio/curious.bio/smart-energy-monitor"
release = "https://code.curious.bio/curious.bio/smart-energy-monitor/releases"

license = "CERN-OHL-S-2.0"
licensor = "Curious Community Labs e. V."

readme = "/README.md"
user-manual = "/docs/energy-monitor/README.md"
manufacturing-instructions = "/docs/energy-monitor/README.md"
contribution-guide = "README.md"

documentation-language = "en"
technology-readiness-level = "OTRL-5"
documentation-readiness-level = "ODRL-3*"

bom = "/hardware/BOM.md"
tsdc = ["STD"]

[[software]]
release = "0.1"
installation-guide = "/docs/energy-monitor/README.md"
